name: Sync Spiders from Upstream Master

on:
  schedule:
    - cron: '0 0 * * 4'  # Runs at 00:00 UTC every Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/alltheplaces/alltheplaces.git
          git fetch upstream master

      - name: Sync spiders folder from upstream master
        run: |
          # Ensure we're on the master branch
          git checkout master
          
          # Fetch upstream master
          git fetch upstream master
          
          # Check if there are changes in the upstream spiders folder
          if git diff --quiet upstream/master:spiders master:spiders; then
            echo "No changes in spiders folder to sync"
          else
            # Checkout only the spiders folder from upstream master
            git checkout upstream/master -- spiders
            
            # Stage the changes
            git add spiders
            
            # Commit if there are changes
            if ! git diff --staged --quiet; then
              git commit -m "Sync spiders folder with upstream master"
              git push origin master
              echo "Changes from upstream master's spiders folder have been synced and pushed"
            else
              echo "No changes to commit after checkout"
            fi
          fi
        shell: /usr/bin/bash -e {0}

      - name: Check for conflicts
        run: |
          if git status | grep -q "You have unmerged paths"; then
            echo "::warning::There are merge conflicts. Please resolve them manually."
            exit 1
          fi