name: Sync Spiders Folder

on:
  schedule:
    - cron: '0 0 * * 4'  # Runs at 00:00 UTC every Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/alltheplaces/alltheplaces.git
          git fetch upstream

      - name: Sync spiders folder
        run: |
          git checkout main
          git checkout upstream/main -- spiders
          if ! git diff --staged --quiet; then
            git commit -m "Sync spiders folder with upstream"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Check for conflicts
        run: |
          if git status | grep -q "You have unmerged paths"; then
            echo "::warning::There are merge conflicts. Please resolve them manually."
            exit 1
          fi